---
title: "Ames_random_forest_analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Random Forest model analysis

Purpose of this file is to bring the imputed file from python and use the variables flushed out by random forest to do analysis on the data 

```{r}
library(VIM)
library(dplyr)
library(mice)
library(caret)
library(ggplot2)
library(Hmisc)
library(car)
ames_house_price_train=read.csv("./data/imputedTrainData.csv",na.strings=c("DNE"),check.names = FALSE)
```

## RF variables


```{r}
x_rf_variables = ames_house_price_train %>%  select( 'GrLivArea',
 'LotFrontage',
 'LotArea',
 'Alley',
 'LotShape',
 'LandSlope',
 'HouseStyle',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'MasVnrArea',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinSF1',
 'BsmtFinType2',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Functional',
 'Fireplaces',
 'FireplaceQu',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageCars',
 'GarageArea',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'Fence',
 'MiscFeature',
 'MiscVal',
 'MoSold',
 'YrSold',
 'MSSubClass_20',
 'MSSubClass_30',
 'MSSubClass_40',
 'MSSubClass_45',
 'MSSubClass_50',
 'MSSubClass_60',
 'MSSubClass_70',
 'MSSubClass_80',
 'MSSubClass_85',
 'MSSubClass_90',
 'MSSubClass_120',
 'MSSubClass_160',
 'MSSubClass_180',
 'MSSubClass_190',
 'MSZoning_C',
 'MSZoning_FV',
 'MSZoning_RH',
 'MSZoning_RL',
 'MSZoning_RM',
 'Street_Pave',
 'LandContour_Low',
 'LandContour_HLS',
 'LandContour_Bnk',
 'LandContour_Lvl',
 'LotConfig_Inside',
 'LotConfig_Corner',
 'LotConfig_CulDSac',
 'LotConfig_FR2',
 'Condition1_Artery',
 'Condition1_Feedr',
 'Condition1_Norm',
 'Condition1_RRAn',
 'Condition1_PosN',
 'Condition1_PosA',
 'Condition1_RRAe',
 'Condition2_Feedr',
 'BldgType_TwnhsE',
 'BldgType_Twnhs',
 'BldgType_Duplex',
 'BldgType_2FmCon',
 'BldgType_1Fam',
 'GasHeating',
 'ModernElectrical',
 'NewHome',
 'Neighborhood_Blmngtn',
 'Neighborhood_BrDale',
 'Neighborhood_BrkSide',
 'Neighborhood_ClearCr',
 'Neighborhood_CollgCr',
 'Neighborhood_Crawfor',
 'Neighborhood_Edwards',
 'Neighborhood_Gilbert',
 'Neighborhood_IDOTRR',
 'Neighborhood_MeadowV',
 'Neighborhood_Mitchel',
 'Neighborhood_NAmes',
 'Neighborhood_NoRidge',
 'Neighborhood_NPkVill',
 'Neighborhood_NridgHt',
 'Neighborhood_NWAmes',
 'Neighborhood_OldTown',
 'Neighborhood_SWISU',
 'Neighborhood_Sawyer',
 'Neighborhood_SawyerW',
 'Neighborhood_Somerst',
 'Neighborhood_StoneBr',
 'Neighborhood_Timber',
 'Neighborhood_Veenker')
```

## Random Forest variables

```{r}
model = lm(log(ames_house_price_train$SalePrice) ~ ., data=x_rf_variables)
summary(model)
plot(model)

```
